### ISSUE TITLE
Malseclogon dump method 3 fails on windows server

### ISSUE THREAD

**Issue by antonioCoco** [antonioCoco/MalSeclogon#1]
Reported from this tweet --> https://twitter.com/SecObscurity/status/1544330172261961730: 

"when i dump the lsass on a server (2012,2016),  mimikatz cannot read the saved dump throwing the error "Error: ERROR kuhl_m_sekurlsa_acquireLSA ; Modules informations". On a workstation works great."

This issue will be used to track any troubleshooting steps.

**Comment by SecurityObscurity** [comment]
Thank you for opening an issue. I've performed a couple of test and i've created a project with only the code needed to dump lsass, that gives me the error mentioned above.

[https://gist.github.com/SecurityObscurity/e712fbd2d55a9e80eb0000f343ca04fa](https://gist.github.com/SecurityObscurity/e712fbd2d55a9e80eb0000f343ca04fa)

Maybe the code can help you. I've tested the code on two instances of Windows Server 2016 version 1607 (OS Build 14393.447).

**Comment by antonioCoco** [comment]
So the bug was when MiniDumpWriteDump is used with the PID parameter as 0, a trick described here --> https://rastamouse.me/dumping-lsass-with-duplicated-handles/

While it worked well for Windows >= 10 it doesn't work for older windows :/

Anyway, i have reused the same trick i use in the other techniques to patch NtOpenProcess in order to avoid an additional open process.

Now should work fine with the commit https://github.com/antonioCoco/MalSeclogon/commit/8f32ee6c2bffd268604224d00469dae440304921.

Feel free to try with the new code, you shouldn't have the bug anymore. 

Thanks for providing your testing code which was crucial and helpful for reproducing the issue!

**Comment by Alcqua** [comment]
Rasta confirmed that he tested the technique mentioned in his blog only on Windows 10, so as you said it doesn't work on  Windows Server from 2008 to 2019. Would be interesting to know why doesn't work, because the dump is saved. Maybe some information about the dump are not saved within the file.

About the NtOpenProcess patching technique, you talk on some fo your blog posts ? just curious to know how it works.

Anyhow, i've tested the new code and it works. Thank you for fixing the bug.

**Comment by SecurityObscurity** [comment]
Rasta confirmed that he tested the technique mentioned in his blog only on Windows 10, so as you said it doesn't work on Windows Server from 2008 to 2019. Would be interesting to know why doesn't work, because the dump is saved. Maybe some information about the dump are not saved within the file.

About the NtOpenProcess patching technique, you talk on some fo your blog posts ? just curious to know how it works.

Anyhow, i've tested the new code and it works. Thank you for fixing the bug.

**Comment by antonioCoco** [comment]
about the NtOpenProcess patching techinque, i quote my blogpost as i cannot find better explanation:

"As shown in the above Demo, a dump of lsass is performed through a leaked handle and saved to the disk. In this case I have used the [MiniDumpWriteDump](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump) function.

One thing we need to consider while using this function is that it tries to open a new handle to lsass and we definitely want to avoid that. The reason for this behavior seems to be inside RtlQueryProcessDebugInformation called internally by MiniDumpWriteDump, it opens a new handle to lsass instead of using the one provided in the call.
 
To solve this issue i have hooked [NtOpenProcess](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-ntopenprocess) before calling MiniDumpWriteDump. In the hooked function the leaked lsass handle is returned instead of forwarding the call to the kernel. 
Another thing to take care of is to prevent the leaked handle from being closed by RtlQueryProcessDebugInformation. We could provide a duplicate of the leaked handle to solve the problem, but we want to avoid that a registered kernel callback is catching our dumping process for the newly duplicated handle.
One smarter thing to do is to use [SetHandleInformation ](https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation)and protect the leaked handle from any closing attempts through the flag HANDLE_FLAG_PROTECT_FROM_CLOSE."

More details here --> https://splintercod3.blogspot.com/p/the-hidden-side-of-seclogon-part-2.html
